"""initial schema

Revision ID: f8c72bfbcdba
Revises: 
Create Date: 2026-09-16 16:21:43.453907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8c72bfbcdba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLES = (
    'profiles',
    'source_documents',
    'chat_threads',
    'document_chunks',
    'chat_messages',
    'message_citations',
)

# Browser clients never write; the backend writes with a privileged connection that bypasses RLS.
# These read policies only exist so user-scoped Supabase clients see their own rows.
READ_POLICIES = {
    'profiles': "id = (select auth.uid())",
    'chat_threads': "user_id = (select auth.uid())",
    'chat_messages': (
        "exists (select 1 from chat_threads t"
        " where t.id = chat_messages.thread_id and t.user_id = (select auth.uid()))"
    ),
    'message_citations': (
        "exists (select 1 from chat_messages m join chat_threads t on t.id = m.thread_id"
        " where m.id = message_citations.message_id and t.user_id = (select auth.uid()))"
    ),
    'source_documents': "true",
    'document_chunks': "true",
}


def upgrade() -> None:
    """Upgrade schema."""
    # Supabase convention: extensions live in the `extensions` schema, which is on the default search_path.
    op.execute("create schema if not exists extensions")
    op.execute("create extension if not exists vector with schema extensions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "alter table profiles add constraint profiles_id_fkey"
        " foreign key (id) references auth.users (id) on delete cascade"
    )
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('accession_number', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('filing_type', sa.Text(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_source_documents_ticker'), 'source_documents', ['ticker'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index')
    )
    op.create_index('document_chunks_embedding_hnsw_idx', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('document_chunks_metadata_gin_idx', 'document_chunks', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('document_chunks_search_vector_gin_idx', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant')", name='chat_messages_role_check'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'position')
    )
    op.create_table('message_citations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'citation_index')
    )
    op.create_index(op.f('ix_message_citations_chunk_id'), 'message_citations', ['chunk_id'], unique=False)
    # ### end Alembic commands ###

    for table in TABLES:
        op.execute(f"alter table {table} enable row level security")
    for table, condition in READ_POLICIES.items():
        op.execute(f"create policy {table}_select on {table} for select to authenticated using ({condition})")
    # Otherwise Supabase exposes Alembic's bookkeeping table through its public API.
    op.execute("alter table alembic_version enable row level security")


def downgrade() -> None:
    """Downgrade schema."""
    # Policies and RLS go away with their tables. The vector extension is left installed on purpose.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_citations_chunk_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_table('chat_messages')
    op.drop_index('document_chunks_search_vector_gin_idx', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('document_chunks_metadata_gin_idx', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('document_chunks_embedding_hnsw_idx', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_source_documents_ticker'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_table('profiles')
    # ### end Alembic commands ###
